### ISSUE TITLE
Exemplo não funciona

### ISSUE THREAD

**Issue by mpena2099** [courtsbr/tjsp#2]
Olá.

Estou tentando rodar o exemplo de utilização e parece estar com algum erro, já que ele chega a criar o diretório /data-raw/cjsg/, mas os arquivos HTML dentro dele (00001.html - 00005.html) contém apenas o seguinte dentro de cada um:

```
<span style="display: none;" id="nomeAbaRetornoFiltro-A" >Acórdãos(0)</span>
<input id="totalResultadoAbaRetornoFiltro-A" type="hidden" value="0" />

		
		
			<div align="center" class="ementaClass" style="padding: 80px;">
				<strong>
					Não foi encontrado nenhum resultado correspondente à busca realizada.
				</strong>
			</div>
```

Gostaria de ajudar para resolver esse problema.

Abraços,
Mauricio de O. Pena

**Comment by mpena2099** [comment]
Bom, progredi um pouco mais, seguindo o exemplo abaixo que encontrei no arquivo cjsg.R:

```
library(tjsp)

s <- cjsg_session()
parms <- cjsg_parms(s, livre = 'acordam')
cjsg_npags(s, parms)
cjsg(s, parms, max_pag = 1, path = '.') # chamada internamente dentro de cjsg.
```

Alterei um pouco ele, de acordo com o exemplo da  pagina inicial, e fiz o seguinte:
```
library(tjsp)
library(tibble)
library(magrittr)

s <- cjsg_session()
parms <- cjsg_parms(s, livre = 'acordam', data_inicial_julg = '2018-11-15', data_final_julg = '2018-11-15')
cjsg_npags(s, parms)
cjsg(s, parms, max_pag = 1, path = 'data-raw/cjsg')
```

Isso fez gerar o arquivo HTML /data-raw/cjsg/00001.html aparentemente correto. Ele contem o mesmo que aparece quando eu faço uma busca pelo site do TJSP. 

Em seguida:

```
# Parse das páginas HTML em uma `tibble`
arqs_cjpg <- dir('data-raw/cjsg', full.names = TRUE)
d_jurisprudencia <- parse_cjsg(arqs_cjpg)
```

Pareceu funcionar também.

Agora, o próxima passo seria baixar os processos. Precisei instalar um package:
```
# Download dos processos obtidos em páginas HTML
install.packages("dplyr")
library(dplyr)

d_result_cposg <- d_jurisprudencia %>%
  distinct(n_processo) %>%
  with(n_processo) %>%
  cposg(path = 'data-raw/cposg')

# Parse das páginas HTML obtidas pelo `cposg`
arqs_cposg <- dir('data-raw/cposg', full.names = TRUE)
d_cposg <- cposg(arqs_cposg)
```

Bom, PARECE que deu certo! Ele criou o dir 'data-raw/cposg' com varrido arquivos HTML referente aos processos lá.

Só tem um porém: eu precisaria dos arquivos PDF. Existe algo que sirva para eu fazer o download dos mesmos?


Abraços,
Mauricio de O. Pena

**Comment by jtrecenti** [comment]
Caro Maurício, use o pacote esaj. O tjsp está desatualizado.

**Comment by mpena2099** [comment]
@jtrecenti , obrigado por avisar. Já estou olhando o esaj e vendo como funciona.
